### ISSUE TITLE
Driver/library version mismatch error

### ISSUE THREAD

**Issue by akshay-ast** [rajeshroy402/DeepStream-6.0-dGPU-Installation#5]
When I type nvidia-smi in the terminal, it says:
Failed to initialize NVML: Driver/Library version mismatch

**Comment by PareshKamble** [comment]
Hi @akshay-ast,
I got the same issue. I found best answer in the given [link](https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch#:~:text=I%20had%20the,reinstall%20cuda%2Bcudnn.).
